editAreaLoader.lang["ru"]={
new_document: "Новый пустой документ",
search_button: "Поиск и замена",
search_command: "Искать следующий / открыть панель поиска",
search: "Поиск",
replace: "Замена",
replace_command: "Заменить / открыть панель поиска",
find_next: "Найти следующее",
replace_all: "Заменить все",
reg_exp: "Регулярное выражение",
match_case: "Учитывать регистр",
not_found: "Не найдено.",
occurrence_replaced: "Вхождение заменено.",
search_field_empty: "Поле поиска пустое",
restart_search_at_begin: "Достигнут конец документа. Начинаю с начала.",
move_popup: "Переместить окно поиска",
font_size: "--Размер шрифта--",
go_to_line: "Перейти к строке",
go_to_line_prompt: "Перейти к строке номер:",
undo: "Отменить",
redo: "Вернуть",
change_smooth_selection: "Включить/отключить некоторые функции просмотра (более красиво, но больше использует процессор)",
highlight: "Переключить подсветку синтаксиса включена/выключена",
reset_highlight: "Восстановить подсветку (если разсинхронизирована от текста)",
help: "О программе",
save: "Сохранить",
load: "Загрузить",
line_abbr: "Стр",
char_abbr: "Стлб",
position: "Позиция",
total: "Всего",
close_popup: "Закрыть всплывающее окно",
shortcuts: "Горячие клавиши",
add_tab: "Добавить табуляцию в текст",
remove_tab: "убрать табуляцию из текста",
about_notice: "Внимание: функция подсветки синтаксиса только для небольших текстов",
toggle: "Вкл/Выкл подсветку",
accesskey: "Горячая клавиша",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "Обработка...",
fullscreen: "Полный экран",
syntax_selection: "--Синтакс--",
syntax_css: "CSS",
syntax_html: "HTML",
syntax_js: "Javascript",
syntax_php: "Php",
syntax_python: "Python",
syntax_vb: "Visual Basic",
syntax_xml: "Xml",
syntax_c: "C",
syntax_cpp: "CPP",
syntax_basic: "Basic",
syntax_pas: "Pascal",
syntax_brainfuck: "Brainfuck",
syntax_sql: "SQL",
syntax_ruby: "Ruby",
syntax_robotstxt: "Robots txt",
syntax_tsql: "T-SQL",
close_tab: "Закрыть файл"
};
